"""
Fully generated by ChatGPT 5.6.

Fast Heston IV Surface Dataset Generator
========================================

Generates synthetic Heston implied-volatility surfaces.

Outputs:
    heston_iv_surfaces.csv
    heston_iv_train.csv
    heston_iv_test.csv

Each surface:
    15 log-moneyness points
    8 maturities
    = 120 points

Train/test split is performed BY SURFACE.
"""

import numpy as np
import pandas as pd

from scipy.optimize import brentq
from scipy.special import ndtr
from tqdm import tqdm


# ================================================================
# HESTON CHARACTERISTIC FUNCTION
# ================================================================

def heston_cf(
    u,
    T,
    v0,
    kappa,
    theta,
    sigma,
    rho,
    logS0=0.0,
    r=0.0,
    q=0.0,
):
    """
    Heston characteristic function:

        E[exp(i*u*log(S_T))]

    Uses the original little-Heston-trap formulation.
    """

    iu = 1j * u

    b = (
        kappa
        -
        rho * sigma * iu
    )

    d = np.sqrt(
        b * b
        +
        sigma * sigma
        *
        (iu + u * u)
    )

    # Choose square-root branch
    d = np.where(
        np.real(d) < 0.0,
        -d,
        d,
    )

    g = (
        b - d
    ) / (
        b + d
    )

    exp_dt = np.exp(
        -d * T
    )

    C = (
        iu
        *
        (
            logS0
            +
            (r - q) * T
        )
        +
        (
            kappa * theta
            / sigma**2
        )
        *
        (
            (b - d) * T
            -
            2.0
            *
            np.log(
                (
                    1.0
                    -
                    g * exp_dt
                )
                /
                (
                    1.0
                    -
                    g
                )
            )
        )
    )

    D = (
        (b - d)
        / sigma**2
        *
        (
            1.0 - exp_dt
        )
        /
        (
            1.0
            -
            g * exp_dt
        )
    )

    return np.exp(
        C + D * v0
    )


# ================================================================
# HESTON PRICES
# ================================================================

def heston_prices(
    strikes,
    T,
    v0,
    kappa,
    theta,
    sigma,
    rho,
    S0=1.0,
    r=0.0,
    q=0.0,
    N=4096,
    umax=200.0,
):
    """
    Vectorized Heston European call prices.
    """

    strikes = np.asarray(
        strikes,
        dtype=float,
    )

    logK = np.log(
        strikes
    )

    logS0 = np.log(
        S0
    )

    # ------------------------------------------------------------
    # Fourier grid
    #
    # Keep this essentially identical to your original version.
    # ------------------------------------------------------------

    u = np.linspace(
        1e-8,
        umax,
        N,
    )

    # ------------------------------------------------------------
    # Characteristic function
    # ------------------------------------------------------------

    phi = heston_cf(
        u,
        T,
        v0,
        kappa,
        theta,
        sigma,
        rho,
        logS0,
        r,
        q,
    )

    # ------------------------------------------------------------
    # Phase
    # ------------------------------------------------------------

    phase = np.exp(
        -1j
        *
        np.outer(
            u,
            logK,
        )
    )

    # ============================================================
    # P2
    # ============================================================

    integrand = np.real(
        phase
        *
        phi[:, None]
        /
        (
            1j
            *
            u[:, None]
        )
    )

    P2 = (
        0.5
        +
        np.trapezoid(
            integrand,
            u,
            axis=0,
        )
        / np.pi
    )

    # ============================================================
    # P1
    # ============================================================

    phi_shifted = heston_cf(
        u - 1j,
        T,
        v0,
        kappa,
        theta,
        sigma,
        rho,
        logS0,
        r,
        q,
    )

    # Analytic value of phi(-i)
    phi_minus_i = (
        S0
        *
        np.exp(
            (r - q) * T
        )
    )

    integrand = np.real(
        phase
        *
        phi_shifted[:, None]
        /
        (
            1j
            *
            u[:, None]
            *
            phi_minus_i
        )
    )

    P1 = (
        0.5
        +
        np.trapezoid(
            integrand,
            u,
            axis=0,
        )
        / np.pi
    )

    # ============================================================
    # Call price
    # ============================================================

    prices = (
        S0
        *
        np.exp(-q * T)
        *
        P1
        -
        strikes
        *
        np.exp(-r * T)
        *
        P2
    )

    return prices


# ================================================================
# BLACK-SCHOLES CALL
# ================================================================

def bs_call(
    S0,
    K,
    T,
    vol,
    r=0.0,
    q=0.0,
):
    """
    Black-Scholes European call price.
    """

    if vol <= 0.0:

        return max(
            S0 * np.exp(-q * T)
            -
            K * np.exp(-r * T),
            0.0,
        )

    sqrtT = np.sqrt(T)

    d1 = (
        np.log(S0 / K)
        +
        (
            r
            -
            q
            +
            0.5 * vol**2
        )
        *
        T
    ) / (
        vol
        *
        sqrtT
    )

    d2 = (
        d1
        -
        vol
        *
        sqrtT
    )

    return (
        S0
        *
        np.exp(-q * T)
        *
        ndtr(d1)
        -
        K
        *
        np.exp(-r * T)
        *
        ndtr(d2)
    )


# ================================================================
# ROBUST IMPLIED VOLATILITY
# ================================================================

def implied_volatility(
    price,
    S0,
    K,
    T,
    r=0.0,
    q=0.0,
):
    """
    Convert a call price into Black-Scholes implied volatility.

    Important:
    We never use 1e-8 as a fallback IV.

    If the Heston price is infinitesimally outside the no-arbitrage
    interval due to Fourier numerical error, we move it slightly
    INTO the interval and invert it normally.
    """

    if not np.isfinite(price):

        return np.nan

    # ------------------------------------------------------------
    # Theoretical price bounds
    # ------------------------------------------------------------

    discounted_spot = (
        S0
        *
        np.exp(-q * T)
    )

    discounted_strike = (
        K
        *
        np.exp(-r * T)
    )

    intrinsic = max(
        discounted_spot
        -
        discounted_strike,
        0.0,
    )

    upper_bound = (
        discounted_spot
    )

    # ------------------------------------------------------------
    # Numerical tolerance
    #
    # We need a tolerance relative to the price scale.
    # ------------------------------------------------------------

    tol = (
        1e-10
        *
        max(
            S0,
            K,
            1.0,
        )
    )

    # ------------------------------------------------------------
    # Tiny numerical error below intrinsic
    # ------------------------------------------------------------

    if price < intrinsic:

        error = (
            intrinsic
            -
            price
        )

        if error <= 100.0 * tol:

            # IMPORTANT:
            #
            # Don't set price = intrinsic.
            #
            # That would imply zero IV and force the root finder
            # toward its lower bound.
            #
            # Instead put it just inside the valid region.
            price = (
                intrinsic
                +
                tol
            )

        else:

            return np.nan

    # ------------------------------------------------------------
    # Tiny numerical error above upper bound
    # ------------------------------------------------------------

    if price > upper_bound:

        error = (
            price
            -
            upper_bound
        )

        if error <= 100.0 * tol:

            price = (
                upper_bound
                -
                tol
            )

        else:

            return np.nan

    # ------------------------------------------------------------
    # Ensure strictly inside bounds
    # ------------------------------------------------------------

    price = np.clip(
        price,
        intrinsic + tol,
        upper_bound - tol,
    )

    # ------------------------------------------------------------
    # Root function
    # ------------------------------------------------------------

    def objective(vol):

        return (
            bs_call(
                S0,
                K,
                T,
                vol,
                r,
                q,
            )
            -
            price
        )

    # ------------------------------------------------------------
    # Bracket
    # ------------------------------------------------------------

    low = 1e-4
    high = 5.0

    f_low = objective(
        low
    )

    f_high = objective(
        high
    )

    # ------------------------------------------------------------
    # If 500% isn't enough, expand.
    # This almost never happens for this parameter range.
    # ------------------------------------------------------------

    while (
        f_low * f_high > 0.0
        and high < 20.0
    ):

        high *= 2.0

        f_high = objective(
            high
        )

    if f_low * f_high > 0.0:

        return np.nan

    # ------------------------------------------------------------
    # Brent root
    # ------------------------------------------------------------

    try:

        iv = brentq(
            objective,
            low,
            high,
            xtol=1e-10,
            rtol=1e-10,
            maxiter=100,
        )

    except ValueError:

        return np.nan

    return iv


# ================================================================
# HESTON IV SURFACE
# ================================================================

def heston_iv_surface(
    strikes,
    maturities,
    v0,
    kappa,
    theta,
    sigma,
    rho,
    S0=1.0,
    r=0.0,
    q=0.0,
    N=4096,
    umax=200.0,
):
    """
    Generate one Heston implied-volatility surface.
    """

    strikes = np.asarray(
        strikes,
        dtype=float,
    )

    maturities = np.asarray(
        maturities,
        dtype=float,
    )

    iv = np.empty(
        (
            len(maturities),
            len(strikes),
        ),
        dtype=float,
    )

    # ------------------------------------------------------------
    # Calculate each maturity
    # ------------------------------------------------------------

    for i, T in enumerate(
        maturities
    ):

        prices = heston_prices(
            strikes,
            T,
            v0,
            kappa,
            theta,
            sigma,
            rho,
            S0=S0,
            r=r,
            q=q,
            N=N,
            umax=umax,
        )

        # --------------------------------------------------------
        # IV inversion
        # --------------------------------------------------------

        for j, (
            K,
            price,
        ) in enumerate(
            zip(
                strikes,
                prices,
            )
        ):

            iv[i, j] = (
                implied_volatility(
                    price,
                    S0,
                    K,
                    T,
                    r,
                    q,
                )
            )

    return iv


# ================================================================
# MAIN
# ================================================================

if __name__ == "__main__":

    # ============================================================
    # RANDOM GENERATOR
    # ============================================================

    rng = np.random.default_rng(
        42
    )

    # ============================================================
    # DATASET CONFIG
    # ============================================================

    n_surfaces = 2**12

    train_fraction = 0.80

    # ------------------------------------------------------------
    # Surface grid
    # ------------------------------------------------------------

    logmoneyness_grid = np.linspace(
        np.log(0.6),
        np.log(1.4),
        15,
    )

    maturities = np.linspace(
        0.1,
        5.0,
        8,
    )

    # ------------------------------------------------------------
    # Market
    # ------------------------------------------------------------

    S0 = 100.0

    r = 0.03

    q = 0.0

    # ------------------------------------------------------------
    # Fourier settings
    #
    # These are the same scale as your original code.
    # ------------------------------------------------------------

    N = 4096

    umax = 200.0

    points_per_surface = (
        len(logmoneyness_grid)
        *
        len(maturities)
    )

    # ============================================================
    # GENERATE
    # ============================================================

    rows = []

    failed_surfaces = []

    print()
    print(
        "Generating Heston surfaces..."
    )

    for surface_id in tqdm(
        range(n_surfaces),
        desc="Surfaces",
    ):

        # --------------------------------------------------------
        # Sample Heston parameters
        # --------------------------------------------------------

        v0 = rng.uniform(
            0.01,
            0.09,
        )

        kappa = rng.uniform(
            0.5,
            5.0,
        )

        theta = rng.uniform(
            0.01,
            0.09,
        )

        sigma = rng.uniform(
            0.1,
            1.0,
        )

        rho = rng.uniform(
            -0.95,
            -0.1,
        )

        # --------------------------------------------------------
        # Strikes
        # --------------------------------------------------------

        strikes = (
            S0
            *
            np.exp(
                logmoneyness_grid
            )
        )

        # --------------------------------------------------------
        # Surface
        # --------------------------------------------------------

        iv_surface = (
            heston_iv_surface(
                strikes,
                maturities,
                v0=v0,
                kappa=kappa,
                theta=theta,
                sigma=sigma,
                rho=rho,
                S0=S0,
                r=r,
                q=q,
                N=N,
                umax=umax,
            )
        )

        # --------------------------------------------------------
        # Check for bad values
        #
        # We don't retry. This keeps the runtime predictable.
        # --------------------------------------------------------

        if not np.isfinite(
            iv_surface
        ).all():

            failed_surfaces.append(
                surface_id
            )

        # --------------------------------------------------------
        # Store
        # --------------------------------------------------------

        for i, T in enumerate(
            maturities
        ):

            for j, logm in enumerate(
                logmoneyness_grid
            ):

                rows.append(
                    {
                        "id": surface_id,

                        # Heston parameters
                        "v0": v0,
                        "kappa": kappa,
                        "theta": theta,
                        "sigma": sigma,
                        "rho": rho,

                        # Surface coordinates
                        "logmoneyness": logm,
                        "maturity": T,

                        # IV
                        "iv": iv_surface[
                            i,
                            j
                        ],
                    }
                )

    # ============================================================
    # DATAFRAME
    # ============================================================

    df = pd.DataFrame(
        rows
    )

    # ============================================================
    # REPORT BAD SURFACES
    # ============================================================

    print()
    print(
        "=========================================="
    )

    print(
        f"Generated surfaces : "
        f"{n_surfaces:,}"
    )

    print(
        f"Failed surfaces    : "
        f"{len(failed_surfaces):,}"
    )

    if failed_surfaces:

        print(
            "Failed surface IDs:"
        )

        print(
            failed_surfaces[:20]
        )

    # ============================================================
    # REMOVE BAD SURFACES
    #
    # Rather than contaminating train/test with NaNs.
    # ============================================================

    if failed_surfaces:

        df = df[
            ~df["id"].isin(
                failed_surfaces
            )
        ].copy()

    # ============================================================
    # VALIDATE IV DATA
    # ============================================================

    if df["iv"].isna().any():

        raise RuntimeError(
            "NaNs remain after removing "
            "failed surfaces."
        )

    if not np.isfinite(
        df["iv"].to_numpy()
    ).all():

        raise RuntimeError(
            "Non-finite IV values remain."
        )

    # ------------------------------------------------------------
    # Diagnostics
    # ------------------------------------------------------------

    print()
    print(
        "IV diagnostics:"
    )

    print(
        f"Minimum IV : "
        f"{df['iv'].min():.12f}"
    )

    print(
        f"Maximum IV : "
        f"{df['iv'].max():.12f}"
    )

    print(
        f"Mean IV    : "
        f"{df['iv'].mean():.12f}"
    )

    print(
        f"IV <= 1e-4 : "
        f"{(
            df['iv'] <= 1e-4
        ).sum():,}"
    )

    print(
        f"IV <= 1e-8 : "
        f"{(
            df['iv'] <= 1e-8
        ).sum():,}"
    )

    # ============================================================
    # SURFACE IDS
    # ============================================================

    valid_surface_ids = (
        df["id"]
        .unique()
    )

    # ------------------------------------------------------------
    # Shuffle surfaces
    # ------------------------------------------------------------

    rng.shuffle(
        valid_surface_ids
    )

    # ------------------------------------------------------------
    # Train/test split
    # ------------------------------------------------------------

    n_valid_surfaces = (
        len(valid_surface_ids)
    )

    n_train = int(
        train_fraction
        *
        n_valid_surfaces
    )

    train_ids = (
        valid_surface_ids[
            :n_train
        ]
    )

    test_ids = (
        valid_surface_ids[
            n_train:
        ]
    )

    # ============================================================
    # CREATE TRAIN
    # ============================================================

    train_df = df[
        df["id"].isin(
            train_ids
        )
    ].copy()

    # ============================================================
    # CREATE TEST
    # ============================================================

    test_df = df[
        df["id"].isin(
            test_ids
        )
    ].copy()

    # ============================================================
    # SORT
    # ============================================================

    sort_columns = [
        "id",
        "maturity",
        "logmoneyness",
    ]

    train_df = (
        train_df
        .sort_values(
            sort_columns
        )
        .reset_index(
            drop=True
        )
    )

    test_df = (
        test_df
        .sort_values(
            sort_columns
        )
        .reset_index(
            drop=True
        )
    )

    # ============================================================
    # LEAKAGE CHECK
    # ============================================================

    train_surface_set = set(
        train_df["id"].unique()
    )

    test_surface_set = set(
        test_df["id"].unique()
    )

    overlap = (
        train_surface_set
        &
        test_surface_set
    )

    if overlap:

        raise RuntimeError(
            "Train/test surface leakage detected."
        )

    # ============================================================
    # SAVE
    # ============================================================

    train_df.to_csv(
        "ivsurfacefitting/datasets/heston_train.csv",
        index=False,
    )

    test_df.to_csv(
        "ivsurfacefitting/datasets/heston_test.csv",
        index=False,
    )

    # ============================================================
    # FINAL REPORT
    # ============================================================

    print()
    print(
        "=========================================="
    )
    print(
        "DATASET COMPLETE"
    )
    print(
        "=========================================="
    )

    print(
        f"Valid surfaces : "
        f"{n_valid_surfaces:,}"
    )

    print(
        f"Train surfaces : "
        f"{len(train_surface_set):,}"
    )

    print(
        f"Test surfaces  : "
        f"{len(test_surface_set):,}"
    )

    print(
        f"Points/surface : "
        f"{points_per_surface:,}"
    )

    print(
        f"Total rows     : "
        f"{len(df):,}"
    )

    print(
        f"Train rows     : "
        f"{len(train_df):,}"
    )

    print(
        f"Test rows      : "
        f"{len(test_df):,}"
    )

    print()
    print(
        "Files:"
    )

    print(
        "  heston_train.csv"
    )

    print(
        "  heston_test.csv"
    )

    print(
        "=========================================="
    )
